### ISSUE TITLE
Outputting Audit Tool parameters

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/asset-manager#169]
For debugging purposes when things fail it would be most helpful if Audit tool could output a structured dump of its parameters - at least all the ones that determine pass or failure.

Each test has the `set_params` function, which could be tapped.

Originated from [archive-ops#654](https://github.com/buda-base/archive-ops/issues/654)

**Comment by jimk-bdrc** [comment]
@TBRC-Travis  With respect to calling,  I'm going for the last option, which uses a property definition to invoke.

Because you can also add console log directives to it like:

`-D DiagLevel=params,properties,stats,feature1 -D ConsoleLogAppend=true -D ConsoleLogFileName=someFileName.log`

I'm also going to implement the as an extension of the current console run. Right now, the work run log is the only file that is output into the argument of the `-l` flag. The console and diagnostics will go into a file named `AuditTest-console-yyyy-mm-dd-hh-MM-ss.txt` (which will be sequenced as in the work run log, PASS-W.....). The file will be one file per run, so it will not have the specific work in its name (the parameters don't change by work)

**Comment by jimk-bdrc** [comment]
@Travis-TBRC See the [tracing and diagnostic options](https://github.com/buda-base/asset-manager/blob/asset-manager-169/audittool/doc/AuditToolOperation-1.0.md#tracing-and-diagnostic-options) in the asset-manager-169 branch for what I'm going to implement.

**Comment by TBRC-Travis** [comment]
@jimk-bdrc what's the advantage of using `-D ConsoleLogFileName=someFileName.log` versus just running `audit-tool -v > someFileName.log`?  

A `-v` flag seems a simpler way of specifying `-D DiagLevel=params,properties,stats,feature1` and the rest could be handled with redirection to an output file.  Am I missing something?

**Comment by jimk-bdrc** [comment]
> @jimk-bdrc what's the advantage of using `-D ConsoleLogFileName=someFileName.log` versus just running `audit-tool -v > someFileName.log`?

It allows audit tool to be shell independent. It also allows reporting on the command line which generated the audit tool, so that the output destination is included in the logging, like any other parameter.

> 
> A `-v` flag seems a simpler way of specifying `-D DiagLevel=params,properties,stats,feature1` and the rest could be handled with redirection to an output file. Am I missing something?

This supports  independently specifying params, properties, stats, and the generic `feature1` independently of each other, to avoid wading through verbiage.  If you just want the command line , and not, say, the complete JVM environment, you could just have that. (I added a keyword for the whole JVM, for intense debugging.)

**Comment by TBRC-Travis** [comment]
Got it.  Makes sense.  Thanks!

**Comment by jimk-bdrc** [comment]
Need to set up pull request automation and project automation to close.
