### ISSUE TITLE
not reading some parameters

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/asset-manager#62]
Tested Audit Tool with following parameters.
* file format .tiff .png .jpg 
* file sequence: double file name, 008 instead of 0008. 
* file zise: above 400kb(webpage) And the result in the out put shows in following csv files.

[output csv.zip](https://github.com/buda-base/asset-manager/files/4163734/output.csv.zip)

and it is able to detect wrong file format, double file name but it seems not able to detect files with file size over 400kb. and another things is, is it able to detect file name where one zero is less like 008 instead of 0008? In output file it seems not able to detect this issue.

**Comment by TBRC-JimK** [comment]
First, please reserve one issue report for one issue. I'll answer the "and another thing" issue in email, separately. This is a board for issues. Please resolve questions through NT and my email (jimk@tbrc.org)

**Comment by TBRC-JimK** [comment]
Hi, please do not start different topic threads inside an issue. 
_and another things is, is it able to detect file name where one zero is less like 008 instead of 0008? In output file it seems not able to detect this issue._

I'll answer this in an email t o NT. If I could have your email, I could include you in the thread.
Thanks. jimk@tbrc.org

**Comment by TBRC-JimK** [comment]
Code did not register File Size test in Test Dictionary
